spring:
  datasource:
    url:   jdbc:postgresql://localhost:5432/logos
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
     hibernate:
       dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

  application:
    name: logos-lms-service
    secret: 5bce874940fd82b367610fcf82bdd85e3a3d36959b4b65b273e5e2a60663f718
    jwt:
      secret-key: AF958BBA8392CF55F31277A95F8082086B5094B6422D171402478DAB3A86FA0E
      user-access-token-expiration: 3600000  # 1 час
      user-refresh-token-expiration: 518400000 # 6 дней
      account-activation-token-expiration: 86400000 # 1 день
      user-course-join-confirmation-token-expiration: 604800000 # 7 дней
      reset-2fa-token-expiration: 900000 # 15 минут
      reset-password-token-expiration: 900000 # 15 минут
      inner-services-token:  eyJhbGciOiJIUzI1NiJ9.eyJyb2xlcyI6WyJTRVJWSUNFIl0sInN1YiI6ImlubmVyX3NlcnZpY2VAbXkuc2VydmljZSIsImlhdCI6MTc0ODUxNDQ2NSwiaXNzIjoiYXV0aC1zZXJ2aWNlIiwiZXhwIjoxNzgwMDUwNDY1fQ.sPPwcMq-5pqH48Mj3oxM9lv6eLMdiEgUDNq6HEk8sN4
    url:
      reset-password: http://localhost:8081/front/logos-lms/api/v1/auth/reset-password
      reset-2fa: http://localhost:8081/front/logos-lms/api/v1/auth/reset-2fa
      activate-account: http://localhost:8080/front/logos-lms/api/v1/auth/activate-account
      get-course-info: front-url
      get-task-info: front-url
      get-course-material-info: front-url
      get-solution-info: front-url
    sender-email: yvgnantnv@yandex.ru
    course-limit-params:
        max-file-amount-for-course-material: 20
        max-file-amount-for-task: 10
        max-file-amount-for-solution: 5
        max-task-and-material-file-amount-for-course: 400
        max-solution-file-amount-for-course: 4000
        max-user-amount-for-course: 101
        max-comment-amount-for-solution: 20
    file-storage:
      base-path: D:\logos-lms

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 400MB

server:
  port: 8080
  servlet:
    context-path: /logos-lms/api/v1
